### ISSUE TITLE
A new line...

### ISSUE THREAD

**Issue by bjorkert** [jonfawcett/LoopFollow#110]
I use a line, 30 minutes back in time to indicate what boluses are not yet affecting the BG. I personally find it useful but I'm not sure if it is anything anyone else would like!?

Example:
![image](https://user-images.githubusercontent.com/12718238/98441546-61883d80-20ff-11eb-9822-f705f8fc2d5b.png)

Another option would be to display the boluses newer than 30 minutes in another color/nuance..

This feature should be optional and perpahs you should be able to set somethinig between 30 and 60 minutes depending on insulin.

**Comment by jonfawcett** [comment]
This is a great idea. I do find myself regularly comparing them to the DIA lines. I addition to the recent ones, I also regularly look at the 4-6 hour ones to see of there are any large doses that might have a little more kick at the end. Your idea for color change would be really cool and we could match it up with the full 6 hour insulin curve. The dots have the ability to use an outside ring color and center color. Maybe we could color shift one of those throughout the DIA time.

**Comment by bjorkert** [comment]
Shifting colors would be great, but all dots in the same dataset/line gets the same color? Having 4 datasets (inactive + 3 levels of activity) would probably do it, hard enough to detect more nuances anyway :) Do you have another solution?

**Comment by jonfawcett** [comment]
Look at the bg graph function in graphs.swift to see how to set colors per dot. That sets for high/low but the same concept could just be applied to time delta prior to current time. Also look at the graph setup function line 153. That turns on the center “hole” display. I am on my phone right now so can’t check what method is needed to set the color of the hole but it shouldn’t be hard to find other autocomplete. I think 3 plus inactive would be perfect and should be noticeable/distinguishable. Might not really need the center hole color for 4 values. Could possibly just with shift the main blue color and/or transparency.

**Comment by bjorkert** [comment]
Ah, found that color-array now, great!

**Comment by bjorkert** [comment]
Work in progress: https://github.com/jonfawcett/LoopFollow/compare/dev...bjorkert:gradient_bolus_dots

Just some random colors and levels, will sort out the usage of TimeInterval.

**Comment by bjorkert** [comment]
Pushed a new commit, found an error in the formula... any suggestions on colors? Levels? 
![image](https://user-images.githubusercontent.com/12718238/98461495-cf3e7300-21ac-11eb-99db-fc7c82c95166.png)

Should it be possible to turn this off? Insulin model needs to be configurable..
Rapid-acting adult (peak = 75 min)
Rapid-acting child (65 min)
Fiasp (55 min)

Screen shot of how the current levels/colors:
![image](https://user-images.githubusercontent.com/12718238/98461560-66a3c600-21ad-11eb-9fb2-308e10cc9e5c.png)

**Comment by jonfawcett** [comment]
I’m already using most of the presets for other items, so we don’t have enough left to use those. An idea would be to adjust the alpha of the blue with a formula rather than specific colors. This would be a full gradient and the 55-75 min peak would all be close enough to probably not worry about selecting the peak. Example:
 
10% alpha is the minimum so you can still see inactive dots... will need to test to see what the minimum should be for best display.
0-65 min ago ranges from 0.1 to 1.0 alpha.
65 to maybe 200min is 1.0 to 0.5
200-355min is 0.5 to 0.1

So you have if, if else, if else, else (for each each time range plus the inactive old ones) and each one has a formula just to convert the min ago to the appropriate alpha. So the first 0-65 would be something like

Alpha = 0.1 * (minAgo / 65) * 10

FYI... something similar could also be used on color creation to give a smooth gradient on the color values also

**Comment by bjorkert** [comment]
New commit with two ranges of gradients:
![image](https://user-images.githubusercontent.com/12718238/98859346-536d5080-2462-11eb-9371-ac3e378097d3.png)

            if iaPercent < 90 {
                colors.append(NSUIColor.systemBlue.withAlphaComponent(CGFloat(0.1 + iaPercent/100)))
            } else {
                colors.append(NSUIColor.systemTeal.withAlphaComponent(CGFloat(iaPercent/100)))
            }

**Comment by jonfawcett** [comment]
Are your dots always shifted off incorrectly in time? It’s difficult to tell with it not being matched to the Bg. But this did give me an idea since this does look like it might be more confusion. What about your original blue line with a simple gradual fade out? All dots from current time to peak line are 100% alpha and then past that fade out gradually down to what you have on the left.

**Comment by jonfawcett** [comment]
I'm getting ready to push a this last idea of fading out baed on DIA. So closing this for now.
