### ISSUE TITLE
Target range boundary values are red, should be green

### ISSUE THREAD

**Issue by yuzhuk** [jonfawcett/LoopFollow#122]
We often coast at 3.9 mmol over night, and these values are shown red on the graph. It would be better to show them green - technically they are part of the target range (only <3.9 is considered hypo).

**Comment by jonfawcett** [comment]
The setting is “low bg display value” which implies <= and not <. If you would like to shift this, change the setting 1 click down. The same applies for the high setting. Additionally because dex and nightscout are both in mg/dl, the underlying data is x18 scale from mmol. Because this rounds to 1 decimal for mmol, the underlying BG value might actually be 70 and your setting is at 71 which both round to 3.9. You should try changing the setting by 1 click down and if that doesn’t change it, try 2 clicks down.

**Comment by yuzhuk** [comment]
Yep, that worked, thanks! Will this affect the "In Range" calculation too?

**Comment by jonfawcett** [comment]
Yes. The red/yellow lines, dots, and high/low stats
