### ISSUE TITLE
Basal out of sync

### ISSUE THREAD

**Issue by tohvanah** [jonfawcett/LoopFollow#130]
The image below shows the Loop Follow and Nightscout out of sync regarding the basal. Both the basal value and basal graph differs. I believe the Nightscout is correct. This is a recurring issue, and self-corrects eventually (or appears to after time).

<img width="485" alt="Napkin 31 03-09-21, 10 03 08 AM" src="https://user-images.githubusercontent.com/1719586/110490797-a7114300-80be-11eb-90ea-14999382dec9.png">

**Comment by jonfawcett** [comment]
A few questions..
- what date is your code from?
- does it always happen at the transition of scheduled basal rates?
- From the behavior of basal (no high temp and 165 prediction) this looks like you’re open loop but it shows you are closed? Can you confirm on the loop phone that you are closed loop? If you are, what is your target range?
- Can you post a screenshot showing the loop pill info from NS?

**Comment by tohvanah** [comment]
The code was downloaded using your bash script on March 6, 2021. 

I definitely notice it happening at the transition of basal rates. I'll have to keep an eye on that.

I'm running it closed loop. We're new to Loop, so I have high/wide correction ranges right now. She's at school, but I think the current correction range is about 130-175.

The loop pill info is below. Loop Follow is still out of sync.

<img width="479" alt="Napkin 31 03-09-21, 10 26 55 AM" src="https://user-images.githubusercontent.com/1719586/110494850-f9079800-80c1-11eb-96a7-6f8bee2ace77.png">

**Comment by jonfawcett** [comment]
Thanks for the additional info. The basal processor is the most complicated in the app because Loop doesn't always close them perfectly and doesn't record schedule basals either. You can see the Loop pill only lists the last event at 2 hours ago for 0 basal. Under normal circumstances, basal is being changed very frequently and any issues like this usually resolve within the next 1-2 loop cycles. But because your target range is so large, Loop is essentially acting like open loop for the majority of the time and not updating even it's recommendations (since there are none). So this is why you're seeing it.

I would suggest you post to the FB group about that target range. Even for new Loopers, it is recommended to usually have a range of 5-10 mg/dl.
