### ISSUE TITLE
Upcoming IOS 15.x: Graphing appears to be broken ...

### ISSUE THREAD

**Issue by scrappy** [jonfawcett/LoopFollow#135]
G'day folks ...

As can be seen in the attached image, things seem a bit wonky ... the BG value is correct, and I have it so that its only pulling from NS, but the graph is a wee bit *smooshed* to the right ...

If I kill and restart the app, I can see the graphes being properly drawn, and then they disappear ... 

Although there is no set data, 15.x is expected for general release early fall, which is fast approaching.

If I can provide more debugging information, am happy to help debug, just not a swift programmer, so no idea where to start ...

Thx

**Comment by jonfawcett** [comment]
I am testing on an iPad with iOS 15 already and have no issues. 

This has happened to others before and it was a time stamp or timezone issue with NS entries, which is most likely the cause. Also, it could be caused by freeaps x if that’s driving your data.

If you’d like to DM me your NS url, I can take a look.

**Comment by scrappy** [comment]
I will DM you separately, but just to give an idea of differences, I'm attaching three images ( smaller then I posted at first ) ... two are my two phones, one is running IOS 15.x with the squished graph, the other is 14.x where glucose is graphed fine and the third is a colleague, also on FreeAPS X, where he gets more complete graphs ... all three are the exact same build ... 

I understand that the IOB/COB/etc data doesn't exist ... I've read the code and from what I can tell, I just need to learn swift ( working on it ) and add a code block to Controllers/Nightscout.swift to match the section where it parse 'loop' data so that it parses 'openaps' data, which should make it compatible with not just FreeAPS X, but also AndroidAPS and regular OpenAPS ... 

I am working with my colleague to determine if we have something different in our nightscout settings that is causing the difference in graphing ... 

![IMG_5174](https://user-images.githubusercontent.com/609712/127694956-ec4664ca-6f8c-45b8-8c33-58e915a2b6bf.PNG)
![IMG_4E8CBC5B93ED-1](https://user-images.githubusercontent.com/609712/127694958-6e3c3077-9167-4b95-a192-787fbaf74086.jpeg)

**Comment by scrappy** [comment]
![Image](https://user-images.githubusercontent.com/609712/127695431-85cdfe50-acd8-420c-9823-4a21e4c4493f.jpeg)

**Comment by jonfawcett** [comment]
The issue is how freeaps x is storing temp basals compared to Loop. In this screenshot, the left is freeapsx and the right is Loop. This structure is entirely different and you will need to write a modification to deal with the difference. What is happening isn't so much the graph getting squished as something getting added with a date that is way earlier than the past 24 hours of the BG graph. So the graph scales to fit it all in. It's probably being treated as 0 epoch (1/1/1970). Because the temp basals are sliced into the scheduled basals, it ends up not displaying anything because this is a filled line graph that requires multiple dots to be able to display. There's a chance if you zoomed in really really far, you'd see a thin vertical line right at the far left. eg. all basals are stacked on top of each other at 0. 


I haven't checked other treatments to see how they're stored, so they may have the same issues. But you can disable the download and/or graphing of all those and just use it for BG if you don't want to modify the code. If you do decide to modify code, I'd appreciate you opening a pull request and doing it to either be automatically detected or be able to add a "freeapsx/loop" toggle switch to flip between the 2 methods.

![Screen Shot 2021-07-30 at 3 46 48 PM](https://user-images.githubusercontent.com/38429455/127704458-639f1598-d7d5-4d51-b27d-e9a84e124d08.png)

**Comment by jonfawcett** [comment]
FYI - closed this since it's not an issue with Loop Follow, but an issue with using an app that it wasn't designed for. You can keep the conversation going on the other feature request thread for freeapsx. But it will require someone that is using freeapsx to step up and do the code
