### ISSUE TITLE
TestFlight

### ISSUE THREAD

**Issue by bmammon** [jonfawcett/LoopFollow#26]
Hi Jon,

Is there any chance you could distribute this app via TestFlight for those who do not have Apple Developer licenses? It would simplify updates and installing the app. Thanks!

**Comment by jonfawcett** [comment]
I thought about putting it in the App Store but it would lose the background refresh functionality, which is ultra important for alerts. I don’t personally have a desire to go down the test flight path both from a time perspective and from how quickly that overwhelmed Spike App with the user growth. But since it’s open source anyone can grab it and post to test flight for others. The issues of building for other people (like with Loop) aren’t really a concern with this.
