### ISSUE TITLE
Graph opens on past values

### ISSUE THREAD

**Issue by DiseaseNO** [jonfawcett/LoopFollow#53]
Hi

Would it be possible to have the graph scrolled all the way to the end when you start the app. It it starting at the first entry, not the last. I would have to scroll all the way to right to get to the latest events. Using mmol-dev.

**Comment by jonfawcett** [comment]
Upon first opening, it should immediately scroll to show the latest BG reading at the halfway point of the graph so it shows half of the prediction on screen and half the prediction off screen to the right. After each BG update, it scrolls the latest reading to center also. If you interrupt the scroll process by swiping during it, there's a chance it won't continue, but otherwise it should always be reset after each reading.

If it isn't doing this, please send a video showing how it is behaving.

**Comment by DiseaseNO** [comment]
You might be right. I will try to remember what I did the next time.
