### ISSUE TITLE
Crash after fresh install, successful build, and entering NS URL

### ISSUE THREAD

**Issue by hummelstrand** [jonfawcett/LoopFollow#57]
Built successfully, disconnected phone, added NS URL (without trailing slash, I believe) and when exiting out of the Settings where I added the NS URL the app crashed. Starting the app again causes it to crash immediately. I guess I made a typo in the URL, but since the app crashes on launch it's kinda hard to know. 
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/2979793/85953353-020b6b80-b970-11ea-90ca-a720ac85c4a1.png">

**Comment by jonfawcett** [comment]
Looks like it's downloading data but there's a problem with the data. In the debug area, please expand entries, then the first entry [0] to send me a screenshot of what the data is.

**Comment by hummelstrand** [comment]
I tried to type the URL three times, without it working correctly. Then checked the logs, and it seems like the iOS keyboard autocorrected my URL and replaced a dash with a period. 

Is it possible to disable the auto-correct in the NS URL field, perhaps the that would avoid things where you know that you've typed the correct URL, but are missing that the keyboard sneakily changes what you've typed?

**Comment by jonfawcett** [comment]
pushing a change to a dev branch shortly for that. But it did have data downloaded. There are 8 entries in the bolus downloaded data. Can you send me a screenshot expanding entries[0] in the debugger to show the data in it?

**Comment by jonfawcett** [comment]
Pushed to dev along with a fix for what also might be the issue of a missing timestamp value. It will attempt to use created_at if timestamp is nil. This can happen if there are entries created manually in NS because it doesn't save the timestamp field that Loop uses. If both happen to be nil, it should skip the processing now without crashing. Are you a Loop user?

**Comment by hummelstrand** [comment]
This is what it looked like, can't seem to see any entries:
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/2979793/85953962-5b759980-b974-11ea-92aa-ce453f369433.png">

**Comment by hummelstrand** [comment]
I've now built it from scratch again. Turned off all switches in "Debug Settings." Re-entered the NS URL, switched to mmol/L and restarted the app. The "Home" screen works fine. But as soon as I turn on the debug switch for Basal, it crashes. When i re-build I get this screen in Xcode.
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/2979793/85954078-41888680-b975-11ea-80d5-25dd4b8c2c7d.png">

Let me know what you need to see.

**Comment by jonfawcett** [comment]
Had to add the same nil detection to basal. Just pushed to dev. Are you a Loop user? None of these should be causing errors with the data Loop uploads to NS.

**Comment by hummelstrand** [comment]
Sorry, should have mentioned that, using G6 and MDI... Still waiting for Omnipod prescription, would have happened in May, but the "Pump Training" was postponed due to Covid-19. 

I add basal using Spike today.

**Comment by jonfawcett** [comment]
So you can use the app, but I would absolutely turn off all of the toggle switches in debug settings in the app until you are running Loop. There will probably be a lot more issues since the data other than BG won't match what Loop sends. Adding via Spike or NS directly does not add the correct data to the database even if it looks the same in Spike or NS For instance, NS adds numbers as string values instead of number values, they don't add he timestamp field, etc. So I won't be spending time fixing things that are only issues for non-Loop users to handle manual entries. But it should work great for BG info until you start Looping. You just won't be able to use any feature or display related to basal, carbs, or bolus.

**Comment by hummelstrand** [comment]
OK, thanks. I was hoping to replace Spike, but I understand if you'll focus on Loop-centric features for now!
