### ISSUE TITLE
Feature request: Add IOB value as a criteria for "Fast drop" alarm

### ISSUE THREAD

**Issue by DiseaseNO** [jonfawcett/LoopFollow#76]
As the title say - is it possible to use IOB to decide whether to alarm for a fast drop. Someting like; if IOB is higher than a value do not alarm. 

We have quite a lot false alarms for drops where IOB is nearly zero and the drop will stop in time.

**Comment by jonfawcett** [comment]
I understand the benefit you explain but it's not an IOB-only situation. It matters significantly where on the DIA curve it is, COB, when/what the carbs were, if basal is cut off and for how long, ISF settings, etc. Rough math example just from a DIA standpoint: if IOB is 1 unit, was it 5 units given 5 hours ago vs 1 unit given 1 minute ago. 1 min ago is immensely more urgent for a fast drop because that 1 unit isn't even acting yet and will just make the drop more significant. But if it was dosing for a Pepsi, it might be completely fine.

I'm going to close this request because I see it as a large risk of not triggering when needed to allow BG alarms to be skipped based on IOB, COB, etc. due to the complexity of their interactions. But I'm happy to discuss this directly in more detail...there are probably other things that can be tweaked either with Loop settings or Loop Follow alerts to help you out in this. Feel free to DM me via the FB group.
