### ISSUE TITLE
Mismatch Loop status NS vs LF 1.0

### ISSUE THREAD

**Issue by VillumsNightscout** [jonfawcett/LoopFollow#77]
The status of (green) Loop is out of sync with NS. NS shows new temp basal inacted while LF shows X. IOB not displayed.
LF version 1.0. 
![image](https://user-images.githubusercontent.com/44088657/88153594-e8271680-cc05-11ea-9720-3f289fb788b5.png)
![image](https://user-images.githubusercontent.com/44088657/88153562-dd6c8180-cc05-11ea-8951-a5a96c5efc5b.png)

**Comment by jonfawcett** [comment]
Because there are other missing loop items (IOB, COB for instance), this appears to just be because Loop was delayed in uploading to nightscout. What I mean is that the BG reading was available so LF downloaded everything, but Loop had not uploaded yet or had not finished uploading everything. This can happen at times and should resolve with the next reading. If it does not resolve or you see it happening repeatedly, please reopen this and DM me your NS url via the FB group.
