### ISSUE TITLE
Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)

### ISSUE THREAD

**Issue by paddingtonil** [jonfawcett/LoopFollow#84]
following sudo gem install cocoapods 
Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)

**Comment by jonfawcett** [comment]
This isn’t an issue with Loop Follow. It is most likely either a temporary internet glitch for ruby gems/cocoa pods or an issue specific to your computer/internet setup. What happens if you try to open those urls directly? Please also try a different internet connection to rule out your ISP and try opening the urls directly on a different device to rule out a firewall or error on your computer... even if you just try doing it from your phone on mobile data it will help diagnose what is causing the issue.
