### ISSUE TITLE
SAGE only refers to 'Sensor start', should count time since both the last 'Sensor Start' and 'Sensor Change'

### ISSUE THREAD

**Issue by bjornoleh** [jonfawcett/LoopFollow#85]
SAGE only refers to 'Sensor start', should count time since both the last Sensor Start and Sensor Change.

sage (Sensor Age)
Calculates the number of days and hours since the last Sensor Start and Sensor Change treatment that was recorded.

https://github.com/nightscout/cgm-remote-monitor/blob/master/README.md#sage-sensor-age

**Comment by jonfawcett** [comment]
It is intentionally only using sensor start. Sensor Change refers to when the sensor was physically changed and I believe NS only uses both for calculations because some people confuse the 2 options. But sensor change is only needed people who do restarts or pre-soak and they should always have a sensor start entry also.
