### ISSUE TITLE
2 Values Below Threshold to Trigger Alarm Triggered 

### ISSUE THREAD

**Issue by bmammon** [jonfawcett/LoopFollow#88]
Occasionally I get woken up in the middle of the night by a false alarm. It is a brief dip below my Low Threshold, likely due to sensor compression. 

Some false alarms could be prevented with an option to have an overnight time period require two values below the Low Threshold before an alarm is triggered.

![231A2BD5-AEA3-46E4-B220-CC9469AF5262](https://user-images.githubusercontent.com/26399567/90515967-3dc4e500-e118-11ea-8c07-e0c929974f25.jpeg)

**Comment by jonfawcett** [comment]
I'm not sure how to reconcile this with times that aren't a compression low when the alarm would need triggered. In this instance, if that was not a compression low the alarm needs to be triggered at 3.9 because they next reading could be an urgent low. I had thought about possibly looking for a large delta to try and determine compression lows, but there are too many variables such as iob, last bolus, age of sensor, etc. As an example, I've seen day 1 sensors show almost exactly like your graph here except the higher readings inaccurate ones and it was correcting itself so the low reading is the accurate one. I'm open to any ideas you might have on how to accurately determine it, because I haven't been able to come up with a solution yet.

**Comment by bmammon** [comment]
Yeah it's tricky! I think the only real solution is to start using a sensor like Eversense which doesn't have compression lows
