### ISSUE TITLE
iOS 14 battery drain

### ISSUE THREAD

**Issue by andrew-dixon** [jonfawcett/LoopFollow#94]
Since updating to iOS 14 LoopFollow drains the battery and makes the device (iPhone 11) very hot. Looking at the battery report in setting I see something like the following:
 
![IMG_3616](https://user-images.githubusercontent.com/7441801/93647968-8ca8b780-fa01-11ea-88d4-37e052448783.jpg)

Removing the app from my device, the temperature dropped immediately and the battery stopped draining.

I've recompiled the app on Xcode 12 and the latest dev commit - "Update: IOS 14 support" - but still had the same issue.

**Comment by jonfawcett** [comment]
The % is inline with what I’d expect. My guess for the heat is your phone was also doing a bunch of updates behind the scenes and Loop Follow put it over the edge because iOS couldn’t kill it. 

Usually a new phone and sometimes a major iOS update will take a day or 2 before things settle down and everything runs smoothly. I’d wait a few days and see if the heat issue improves. Going to close this for now, but can take a look into it further if it continues
